---
abstract: 'XSLT transformations with Plack'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
build_requires:
  File::Touch: 0
  HTTP::Request::Common: 0
  XML::LibXML::Cache: 0.12
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-XSLT
recommends:
  XML::LibXML::Cache: 0.12
requires:
  Plack: 0
  Try::Tiny: 0
  XML::LibXML: 1.62
  XML::LibXSLT: 1.62
  perl: 5.008
resources:
  repository: http://github.com/nwellnhof/Plack-Middleware-XSLT
version: 0.30
